spring.application.name=Products Management

server.port=9000
spring.datasource.url=jdbc:postgresql://localhost:5432/products
spring.datasource.username=products
spring.datasource.password=products
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:database/migrations

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=always
logging.level.org.springframework.web=debug
logging.level.org.springframework.security=debug
logging.level.org.springframework.data=debug

jwt.issuer=Shopex
jwt.audience=Shopex
jwt.access_token.expiration.duration=600
jwt.secret=KC7Susfk7y3pAB3o5kUjhRfh4pVuKvwSn5ZT1EhJv34=
