CREATE TABLE IF NOT EXISTS USERS_ROLES(
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    CONSTRAINT USERS_ROLES_PK PRIMARY KEY (user_id, role_id),
    CONSTRAINT USERS_ROLES_USER_FK FOREIGN KEY (user_id) REFERENCES USERS(user_id),
    CONSTRAINT USERS_ROLES_ROLE_FK FOREIGN KEY (role_id) REFERENCES ROLES(role_id)
);